from typing import Any, Iterable, Iterator, TypeVar, Generic, Optional

_T = TypeVar("_T")


class tqdm(Iterator[_T], Generic[_T]):
    def __init__(self, iterable: Optional[Iterable[_T]] = None, *args: Any, **kwargs: Any) -> None: ...
    def __next__(self) -> _T: ...
    def update(self, n: int) -> None: ...
    @classmethod
    def write(self, message: str, end: str = ...) -> None: ...
